host: localhost:8080
info:
  contact: {}
  description: Gin swagger
  title: Gaming Service Gin swagger
  version: "1.0"
paths:
  /api/lol/{country}/match/{matchID}:
    get:
      parameters:
      - description: 國家
        in: path
        name: country
        required: true
        type: string
      - description: 比賽ID
        in: path
        name: matchID
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 取得單賽事詳細資料
      tags:
      - LoL Match
  /api/lol/{country}/match/{matchID}/timeline:
    get:
      parameters:
      - description: 國家
        in: path
        name: country
        required: true
        type: string
      - description: 比賽ID
        in: path
        name: matchID
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 取得單賽事時間線
      tags:
      - LoL Match
  /api/lol/{country}/user/byname/{name}/base:
    get:
      parameters:
      - description: 國家
        in: path
        name: country
        required: true
        type: string
      - description: 遊戲名稱
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 取得玩家資訊，透過遊戲名稱
      tags:
      - LoL User
  /api/lol/{country}/user/bypuuid/{puuid}/matchs:
    get:
      parameters:
      - description: 國家
        in: path
        name: country
        required: true
        type: string
      - description: puuid
        in: path
        name: puuid
        required: true
        type: string
      - description: 筆數
        in: query
        name: count
        type: string
      produces:
      - application/json
      responses: {}
      summary: 取得玩家賽事列表，透過 puuid
      tags:
      - LoL User
  /api/lol/assets/items:
    get:
      parameters:
      - description: 版本號
        in: query
        name: version
        type: string
      - description: 語系
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses: {}
      summary: 取得全部道具
      tags:
      - LoL Assets
  /api/lol/assets/role/{name}:
    get:
      parameters:
      - description: 英雄名稱
        in: path
        name: name
        required: true
        type: string
      - description: 版本號
        in: query
        name: version
        type: string
      - description: 語系
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses: {}
      summary: 取得單英雄詳細資料
      tags:
      - LoL Assets
  /api/lol/assets/roles:
    get:
      parameters:
      - description: 版本號
        in: query
        name: version
        type: string
      - description: 語系
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses: {}
      summary: 取得全英雄
      tags:
      - LoL Assets
  /api/lol/assets/summoners:
    get:
      parameters:
      - description: 版本號
        in: query
        name: version
        type: string
      - description: 語系
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses: {}
      summary: 取得全部召喚師技能
      tags:
      - LoL Assets
  /api/version:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get Version
      tags:
      - Version
swagger: "2.0"
