host: localhost:8080
info:
  contact: {}
  description: Gin swagger
  title: Gaming Service Gin swagger
  version: "1.0"
paths:
  /api/lol/assets/roles:
    get:
      parameters:
      - description: 版本號
        in: query
        name: version
        type: string
      - description: 語系
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get Roles
      tags:
      - Assers
  /api/version:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get Version
      tags:
      - Version
swagger: "2.0"
